/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_jni_ffmpegandroid_ffmpeg */

#ifndef _Included_app_jni_ffmpegandroid_ffmpeg
#define _Included_app_jni_ffmpegandroid_ffmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_jni_ffmpegandroid_ffmpeg
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_jni_ffmpegandroid_ffmpeg_initialize
  (JNIEnv *, jobject);

/*
 * Class:     app_jni_ffmpegandroid_ffmpeg
 * Method:    dump
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_jni_ffmpegandroid_ffmpeg_dump
  (JNIEnv *, jobject, jstring);

/*
 * Class:     app_jni_ffmpegandroid_ffmpeg
 * Method:    media_length
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_app_jni_ffmpegandroid_ffmpeg_media_1length
  (JNIEnv *, jobject, jstring);

/*
 * Class:     app_jni_ffmpegandroid_ffmpeg
 * Method:    scale_media
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_jni_ffmpegandroid_ffmpeg_scale_1media
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
