/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_jni_ffmpegandroid_ffmpeglib_FFmpegLibraryCallback */

#ifndef _Included_app_jni_ffmpegandroid_ffmpeglib_FFmpegLibraryCallback
#define _Included_app_jni_ffmpegandroid_ffmpeglib_FFmpegLibraryCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
