/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_jni_androidffmpeg_ffmpeg */

#ifndef _Included_app_jni_androidffmpeg_ffmpeg
#define _Included_app_jni_androidffmpeg_ffmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_jni_androidffmpeg_ffmpeg
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_jni_androidffmpeg_ffmpeg_initialize
  (JNIEnv *, jobject);

/*
 * Class:     app_jni_androidffmpeg_ffmpeg
 * Method:    ffmpeg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_jni_androidffmpeg_ffmpeg_ffmpeg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     app_jni_androidffmpeg_ffmpeg
 * Method:    media_length
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_app_jni_androidffmpeg_ffmpeg_media_1length
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
